// ALU Module
// Generated by VerilogDesignAgent
// Description: 
设计一个32位ALU（算术逻辑单元），支持以下操作：
- 加法 (ADD)
- 减法 (SUB) 
- 按位与 (AND)
- 按位或 (OR)
- 按位异或 (XOR)
- 按位非 (NOT)
- 左移 (SHL)
- 右移 (SHR)

要求：
- 32位数据位宽
- 4位操作码
- 包含零标志和溢出标志输出
- 同步复位设计


module alu (
    input wire clk,
    input wire rst_n,
    input wire [31:0] data_in,
    output reg [31:0] data_out
);

    // Internal signals
    reg [31:0] internal_reg;
    
    // Main logic
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            data_out <= 32'b0;
            internal_reg <= 32'b0;
        end else begin
            internal_reg <= data_in;
            data_out <= internal_reg;
        end
    end

endmodule